services:
  - type: web
    name: secure-exam-system-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: CORS_ORIGIN
        sync: false
      - key: ADMIN_NAME
        value: Admin User
      - key: ADMIN_EMAIL
        value: admin@exam.com
      - key: ADMIN_PASSWORD
        sync: false

  - type: static
    name: secure-exam-system-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://secure-exam-system-0qja.onrender.com/api
